spring:
  profiles:
<<<<<<< HEAD
<<<<<<< HEAD
    #active : local
    active : dev
=======
    active : local
    #active : dev
>>>>>>> develop
=======
    active: "local"
    #active: "dev"
>>>>>>> master
