spring:
  application:
    name: api
  main:
    banner-mode: log
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #jdbc-url: jdbc:mysql://localhost:3306/mad?useUnicode=true&characterEncoding=utf-8
    jdbc-url: jdbc:mysql://localhost:3306/mad?autoReconnect=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false&passwordCharacterEncoding=UTF8
    username:
    password:
    minimum-idle: 20
    maximum-pool-size: 5
    connection-timeout: 10000
    idle-timeout: 600000
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 10
        temp:
          use_jdbc_metadata_defaults: false
      defer-datasource-initialization: true
  devtools:
    livereload:
      enabled: true
  mvc:
    contentnegotiation:
      favor-parameter: true
      favor-path-extension: false
server:
  port: 8080
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: TRACE
  config: classpath:logback-spring.xml
springdoc:
  swagger-ui:
    enabled: true
    path: /bookmoment-swagger.html
  api-docs:
    path: /v3/api-docs
  paths-to-match: /api/**
